### ISSUE TITLE
Conteúdo de tipos de variáveis para o artigo.

### ISSUE THREAD

**Issue by joseaudicio4** [luisfl04/Historia-da-linguagem-c#4]
*Tem alguma sugestão? Diga abaixo.*
Sim, Minha sugestão é que seja feita a adição de um conteúdo sobre os tipos de variáveis no artigo. Com certeza isso contribuiria muito para futuros leitores.

*Tem um problema a relatar? Diga abaixo*
Não, só uma sugestão.

**Comment by luisfl04** [comment]
Muito bem pensado José! Irei adicionar agora mesmo.
