### ISSUE TITLE
Criação de programas com exemplos de códigos

### ISSUE THREAD

**Issue by joseaudicio4** [luisfl04/Historia-da-linguagem-c#5]
*Tem alguma sugestão? Diga abaixo.*
Sim, uma boa implementação para o artigo seria fazer exemplos de programas que resolvem algum determinado problema usando a linguagem C. Acho que isso faria com que o leitor do artigo se familiariza-se mais com a linguagem e fique mais entusiasmado com o seu uso.

*Tem um problema a relatar?Diga abaixo*
N/A.

**Comment by luisfl04** [comment]
Boa idéia José! Entendi o seu pensamento. Você pode implementar isso pra mim?

**Comment by joseaudicio4** [comment]
Certo, irei criar um fork e submeter uma pull request.
